version: '3.8'

services:
  gamehub:
    build:
      dockerfile: /Dockerfile
    ports:
      - "7024:8080"
      - "7023:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7023
      - ASPNETCORE_Kestrel__Certificates__Default__Password=gamehub123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gamehub.pfx
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https/
  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - "3000:80"
      - "25:25"
    environment:
      - ServerOptions__HostName=smtp4dev
